### ISSUE TITLE
Chart displaying Internet Users x Year x Country

### ISSUE THREAD

**Issue by Alais29** [Alais29/femhack-frontend-challenge#8]
The chart displays how many Internet Users each specific Country could access the Internet per Year. The user should have the ability to change the Country or Year at any time.

**Comment by Dereemii** [comment]
Endpoint 2 

`http://localhost:8080/docs#/default/get_data_from_country_country__country_name__get`

**Comment by Alais29** [comment]
![Image](https://github.com/Alais29/femhack-frontend-challenge/assets/28829550/ebf51d94-535a-40ef-b010-b4cd512c3971)

**Comment by Alais29** [comment]
Endpoint 1: http://localhost:8080/docs#/default/get_countries_countries_get

To get the list of the countries for the select input
